#!/bin/bash
set -x
export ANDROID_HOME=/opt/Android/Sdk
npm i -g appium
cd /opt&&\
wget https://chromedriver.storage.googleapis.com/83.0.4103.14/chromedriver_linux64.zip -O chromedriver.zip &&\
unzip chromedriver.zip&&\
rm chromedriver.zip
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /opt/Android/Sdk/tools/bin/sdkmanager --install 'system-images;android-30;default;x86_64'
rm -rf /opt/androidhome/avd/*
echo no | JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /opt/Android/Sdk/tools/bin/avdmanager create avd -n testAVD -k 'system-images;android-30;default;x86_64'
cp /build/etc/testAVD.ini /opt/androidhome/avd/testAVD.ini
chown -R developer.developer /opt/androidhome
# tools/runAndroid


