#!/bin/bash
set -xe
sudo cp target/*.war /var/lib/tomcat9/webapps/angulartest-server.war
while ! test -d /var/lib/tomcat9/webapps/angulartest-server
do
  echo waiting for tomcat
  sleep 1
done
sudo cp etc/angulartest-server.xml /etc/tomcat9/Catalina/localhost/angulartest-server.xml

