#!/bin/bash
set -e
VERSION=$(grep '"version":' package.json |sed 's/^.*://;s/[ ",]//g')
echo $VERSION >VERSION
sed -i 's~\(<widget.* version="\)[^"]*"\(.*\)$~\1'$(cat VERSION)'"\2~' config.xml
sed -i 's/versionName ".*"/versionName "'$VERSION'"/' etc/build.gradle
